name: Build and Test (All Branches)

on:
  push:
    branches:
      - main
      - feature/**
      - bug/**
      - hotfix/**
  pull_request:
    branches:
      - main
      - feature/**
      - bug/**
      - hotfix/**

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Restore dependencies
      run: dotnet restore CloudStorageORM.sln

    - name: Build solution
      run: dotnet build CloudStorageORM.sln --configuration Release --no-restore

    - name: Run tests
      run: dotnet test CloudStorageORM.sln --configuration Release --no-build --logger "trx"
