name: Publish to NuGet

on:
  push:
    tags:
      - 'v*.*.*' 

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x

    - name: Extract version from tag
      id: vars
      run: echo "PACKAGE_VERSION=${GITHUB_REF#refs/tags/v}" >> $GITHUB_ENV

    - name: Restore dependencies
      run: dotnet restore CloudStorageORM.sln

    - name: Build solution
      run: dotnet build CloudStorageORM.sln --configuration Release --no-restore

    - name: Pack NuGet package
      run: dotnet pack src/CloudStorageORM/CloudStorageORM.csproj --configuration Release --no-build --output ./nupkg /p:PackageVersion=${{ env.PACKAGE_VERSION }}

    - name: Push to NuGet
      run: dotnet nuget push ./nupkg/*.nupkg --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json
